### ISSUE TITLE
crash with sophisticated backpacks being in chest slot

### ISSUE THREAD

**Issue by Tsumiki129** [Mysticpasta1/Dimension-Atlantis#101]
wen wearing the backpack from sophisticated backpacks and a full set of any armour vanilla or Atlantis the game crashes the other mod is designed to go in the chest slot and is fine alone but wen added to Atlantis mod and holding a pice of armore with a full set of any armor on and bag in chest slot the Atlantis mod crashes game.
here is my crash log with just the 2 mods together
[crash-2024-01-18_23.49.27-server.txt](https://github.com/DimensionalDevelopment/atlantis/files/13982753/crash-2024-01-18_23.49.27-server.txt)

**Comment by Mysticpasta1** [comment]
tell this to the other dev, they are trying to cast into my classes which shouldn't happen

**Comment by P3pp3rF1y** [comment]
Sorry, but what's happening here is that you are trying to cast any item in armor slot to ArmorItem despite the fact that any item (not only the ones that inherit from ArmorItem) can go in armor slots when they are marked as such using `getEquipmentSlot` method. So because BackpackItem doesn't inherit from ArmorItem the code below crashes. I am pretty sure that would crash with vanilla Elytra as well btw

https://github.com/DimensionalDevelopment/atlantis/blob/e9d460c8215116e3023096d1c8e672a5ec0967e7/src/main/java/com/mystic/atlantis/items/armor/ItemArmorAtlantis.java#L80

**Comment by Mysticpasta1** [comment]
ah thanks I didn't realize it was on my end I will fix it
